# Generated by Django 5.2.9 on 2025-12-02 15:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLocationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('driver_assigned', 'Driver Assigned'), ('pickup_confirmed', 'Pickup Confirmed'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled_by_customer', 'Cancelled by Customer'), ('cancelled_by_driver', 'Cancelled by Driver'), ('disputed', 'Disputed')], default='pending', max_length=30)),
                ('pickup_address', models.TextField()),
                ('pickup_city', models.CharField(max_length=100)),
                ('pickup_state', models.CharField(max_length=100)),
                ('pickup_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('pickup_lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('pickup_contact_name', models.CharField(max_length=200)),
                ('pickup_contact_phone', models.CharField(max_length=20)),
                ('delivery_address', models.TextField()),
                ('delivery_city', models.CharField(max_length=100)),
                ('delivery_state', models.CharField(max_length=100)),
                ('delivery_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('delivery_lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('delivery_contact_name', models.CharField(max_length=200)),
                ('delivery_contact_phone', models.CharField(max_length=20)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('scheduled_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('highest_category_multiplier', models.DecimalField(decimal_places=2, max_digits=4)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('driver_earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('driver_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('dispute_reason', models.TextField(blank=True, null=True)),
                ('dispute_resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.IntegerField(default=1)),
                ('photo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=30, null=True)),
                ('to_status', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
