# Generated by Django 5.2.9 on 2025-12-02 15:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_reference', models.CharField(max_length=100, unique=True)),
                ('payment_type', models.CharField(choices=[('commitment_fee', 'Commitment Fee'), ('final_payment', 'Final Payment'), ('refund', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('paystack_reference', models.CharField(max_length=200, unique=True)),
                ('paystack_access_code', models.CharField(blank=True, max_length=200, null=True)),
                ('paystack_authorization_url', models.CharField(blank=True, max_length=500, null=True)),
                ('paystack_callback_data', models.JSONField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_channel', models.CharField(blank=True, max_length=50, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payout_reference', models.CharField(max_length=100, unique=True)),
                ('payout_type', models.CharField(choices=[('pickup_milestone', 'Pickup Milestone'), ('delivery_milestone', 'Delivery Milestone'), ('cancellation_compensation', 'Cancellation Compensation')], max_length=30)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('released', 'Released'), ('held', 'Held'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
