# Generated by Django 5.2.9 on 2025-12-03 12:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_verification_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='vehicle_photo',
        ),
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo_url', models.CharField(max_length=500)),
                ('photo_order', models.IntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('driver_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_photos', to='users.driverprofile')),
            ],
            options={
                'ordering': ['photo_order', 'created_at'],
            },
        ),
    ]
