# Generated by Django 5.2.9 on 2025-12-03 14:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('driver', 'Driver'), ('both', 'Both')], max_length=10)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Waiting List Entry',
                'verbose_name_plural': 'Waiting List Entries',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
